import type { ReactNode } from "react";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const Shell = ({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) => (
  <main className="legal-page">
    <header className="legal-nav">
      <Link to="/" className="intro-brand"><span className="brand-symbol">∞</span><span><strong>Infinity Labs</strong><small>Technologies LLC</small></span></Link>
      <Link to="/" className="legal-back"><ArrowLeft size={15}/> Back to company</Link>
    </header>
    <section className="legal-hero"><span>{eyebrow}</span><h1>{title}</h1><p>Last updated: October 8, 2026</p></section>
    <article className="legal-content">{children}<p className="legal-notice"><strong>Important:</strong> This page is a general product-policy draft, not legal advice. Before publishing, confirm the company details, contact address, applicable jurisdictions, and operational practices with qualified counsel.</p></article>
  </main>
);

export function TermsOfService() {
  return <Shell title="Terms of Service" eyebrow="LEGAL / TERMS">
    <p className="legal-intro">These Terms explain the rules for accessing and using websites, applications, and services provided by Infinity Labs Technologies LLC, including NexusFlow (collectively, the “Services”). By accessing or using the Services, you agree to these Terms on behalf of yourself or the organization you represent. If you do not agree, do not use the Services.</p>
    <h2>1. Eligibility and authority</h2><p>You must be legally able to enter into a binding agreement to use the Services. If you use NexusFlow for a company or other organization, you confirm that you have authority to accept these Terms for that organization. You must provide accurate account information and keep it reasonably up to date.</p>
    <h2>2. Accounts and workspace security</h2><p>You are responsible for protecting your credentials, limiting access to authorized people, and notifying your workspace administrator promptly if you suspect unauthorized access. You are responsible for activities performed through your account, except where applicable law provides otherwise. Workspace administrators may invite users, assign roles, and manage organizational access.</p>
    <h2>3. Acceptable use</h2><p>You may use the Services only for lawful business and collaboration purposes. You must not attempt to access another user's account or data without authorization; probe, disrupt, or overload the platform; introduce malware; reverse engineer or circumvent security controls except where law permits; use the Services to infringe rights; or use them for fraud, harassment, unlawful surveillance, or other illegal activity.</p>
    <h2>4. Workspace content and data</h2><p>Your organization and its users retain their rights in content they submit, including customer records, project information, tasks, appointments, and files (“Customer Content”). You authorize us to host, process, transmit, back up, and display Customer Content only as reasonably necessary to provide, protect, maintain, and support the Services and as otherwise instructed by your organization or permitted by law. You are responsible for ensuring that you have the rights and permissions needed to submit the content.</p>
    <h2>5. Privacy and personal information</h2><p>Our handling of personal information is described in the Privacy Policy. Organizations using NexusFlow should ensure they have an appropriate legal basis and required notices or permissions for information entered into their workspace. Do not submit sensitive personal information unless the Services are expressly configured and authorized to handle it.</p>
    <h2>6. Intellectual property</h2><p>The Services, software, visual design, branding, and related materials are owned by Infinity Labs Technologies LLC or its licensors and are protected by applicable intellectual-property laws. Subject to these Terms, we grant you a limited, non-exclusive, non-transferable right to use the Services for your internal business purposes during your authorized access. No ownership is transferred to you.</p>
    <h2>7. Third-party services</h2><p>The Services may interoperate with third-party products, websites, or infrastructure. Third-party services are governed by their own terms and policies. We are not responsible for third-party services that we do not control, and their availability may affect certain features.</p>
    <h2>8. Availability, maintenance, and changes</h2><p>We aim to keep NexusFlow reliable and secure, but we do not guarantee uninterrupted or error-free availability. We may perform maintenance, update features, address security issues, or modify parts of the Services. Where reasonably practical, we will provide notice of material changes that significantly affect normal use.</p>
    <h2>9. Fees and subscriptions</h2><p>If a feature or plan has a fee, the applicable pricing, billing period, taxes, renewal, and cancellation terms will be presented separately before purchase. Unless an applicable order or written agreement says otherwise, paid features are subject to those disclosed terms. No payment obligation should be inferred from this section alone.</p>
    <h2>10. Suspension and termination</h2><p>You may stop using the Services at any time. We may suspend or restrict access when reasonably necessary to protect the Services or users, respond to a security incident, comply with law, address a material breach, or resolve a payment issue under applicable plan terms. Where appropriate and practical, we will provide notice and an opportunity to remedy the issue.</p>
    <h2>11. Disclaimers</h2><p>To the extent permitted by law, the Services are provided on an “as available” basis. We do not warrant that every feature will meet every business requirement or that all defects can be corrected immediately. Nothing in these Terms excludes a warranty or right that cannot lawfully be excluded.</p>
    <h2>12. Limitation of liability</h2><p>To the extent permitted by applicable law, neither party will be liable for indirect, incidental, special, consequential, or punitive losses, or loss of profits, revenue, goodwill, or data arising from use of the Services. Any limits or exclusions apply only to the extent enforceable under the law that governs the relationship and do not exclude liability that cannot legally be limited.</p>
    <h2>13. Indemnity</h2><p>To the extent permitted by law, you are responsible for claims arising from your unlawful use of the Services, your violation of these Terms, or Customer Content that infringes another party's rights. This section does not apply where the law prohibits such an allocation of responsibility.</p>
    <h2>14. Changes to these Terms</h2><p>We may revise these Terms as the Services evolve or legal requirements change. The updated date will appear at the top of this page. If a change is material, we will take reasonable steps to notify users. Continued use after an effective update means you accept the revised Terms, where permitted by law.</p>
    <h2>15. Governing law and disputes</h2><p>The governing law, venue, and dispute-resolution process must be specified in the final version of these Terms based on the company's actual legal arrangements and applicable law. Nothing here removes any mandatory consumer or other rights that apply by law.</p>
    <h2>16. Contact</h2><p>For questions about these Terms, contact Infinity Labs Technologies LLC through the official contact channel published on the company website. Replace this instruction with a monitored legal or support email and the appropriate business address before publication.</p>
  </Shell>;
}

export function PrivacyPolicy() {
  return <Shell title="Privacy Policy" eyebrow="LEGAL / PRIVACY">
    <p className="legal-intro">This Privacy Policy describes how Infinity Labs Technologies LLC handles information in connection with its websites and NexusFlow services. It explains the types of information that may be processed, why it is used, and the choices available to users. The exact practices should be confirmed against the live product and applicable privacy laws before this policy is published.</p>
    <h2>1. Scope and roles</h2><p>This Policy applies to information processed through the company website and NexusFlow. Depending on the situation, your organization may decide why workspace information is processed, while Infinity Labs may process it to provide the platform. The roles and obligations of each party should be documented in applicable customer agreements.</p>
    <h2>2. Information we may collect</h2><p>Information may include account details such as name, email address, authentication records, organization and role; workspace information such as customers, projects, tasks, appointments, notifications, and activity logs; communications you send to support; and technical data such as browser type, device information, diagnostic events, and security logs. Only collect fields and telemetry that the product actually uses.</p>
    <h2>3. How we use information</h2><p>Information may be used to create and administer accounts, authenticate users, provide workspace features, associate users with organizations, respond to support requests, maintain service reliability, detect abuse, protect security, troubleshoot errors, comply with legal obligations, and improve the product. We should not use customer workspace content for unrelated purposes without an appropriate basis and notice.</p>
    <h2>4. Legal bases and permissions</h2><p>Where required by law, processing must rely on an applicable legal basis, such as providing a requested service, meeting a legal obligation, pursuing legitimate interests, or obtaining consent. The appropriate basis depends on the data, the user, the organization, and the jurisdiction. Consent can be withdrawn where consent is the basis, subject to legal limitations.</p>
    <h2>5. Workspace and customer data</h2><p>Workspace content is processed to provide the features requested by the organization and its users. Organization administrators may be able to access or manage workspace content according to their role and product permissions. Users should avoid entering information they are not authorized to share and should follow their organization's retention and access policies.</p>
    <h2>6. Cookies and similar technologies</h2><p>The website or application may use essential storage or similar technologies to maintain sessions, remember preferences, and protect accounts. If analytics, advertising, or other non-essential technologies are added, this Policy and any required consent controls should be updated to describe them accurately.</p>
    <h2>7. Sharing and service providers</h2><p>Information may be shared with authorized infrastructure, hosting, security, support, or other service providers only as needed to operate the Services; with your organization and authorized workspace administrators; when required by law or valid legal process; or in connection with a business reorganization subject to appropriate safeguards. We do not sell personal information unless a future practice and applicable law are explicitly disclosed here.</p>
    <h2>8. International transfers</h2><p>Information may be processed in countries other than where a user lives, depending on hosting and service-provider locations. Where cross-border transfer rules apply, appropriate safeguards and transfer mechanisms must be put in place and described as required by law.</p>
    <h2>9. Security</h2><p>We aim to use reasonable technical and organizational measures to protect information, such as access controls, authentication safeguards, monitoring, and secure operational practices. No system can be guaranteed completely secure. Users and administrators should protect credentials, use appropriate permissions, and report suspected incidents promptly.</p>
    <h2>10. Retention and deletion</h2><p>Information should be retained only for as long as reasonably needed for the purposes described in this Policy, contractual requirements, security, dispute resolution, and legal obligations. Retention periods may differ by data type. Workspace administrators should understand how account closure, export, backup retention, and deletion operate in the deployed product; these details must be confirmed before publication.</p>
    <h2>11. Your privacy rights and choices</h2><p>Depending on your location and applicable law, you may have rights to request access to, correction of, deletion of, restriction of, or a portable copy of personal information, or to object to certain processing. You may also have the right to complain to a data-protection authority. Requests concerning organization-managed workspace data may need to be coordinated with your employer or workspace administrator.</p>
    <h2>12. Children</h2><p>NexusFlow is intended for business use and is not designed for children to create independent accounts. If you believe a child has provided personal information inappropriately, contact the company so the situation can be reviewed and handled as required by law.</p>
    <h2>13. Third-party links and integrations</h2><p>The Services may link to third-party websites or integrate with external tools. Their privacy practices are governed by their own policies, and we encourage users to review those policies before sharing information with them.</p>
    <h2>14. Changes to this Policy</h2><p>We may update this Policy when product features, data practices, or legal requirements change. We will update the date at the top of the page and, where required, provide additional notice or obtain consent.</p>
    <h2>15. Contact and requests</h2><p>For privacy questions or requests, contact Infinity Labs Technologies LLC through the official contact channel on the company website. Before launch, publish a monitored privacy email or request form and add any required company address and data-protection contact details.</p>
  </Shell>;
}
