import { FormEvent, useState } from "react";
import { ArrowRight, Infinity } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Register() {
  const { register }=useAuth(); const nav=useNavigate(); const [form,setForm]=useState({name:"",email:"",password:"",companyName:""}); const [error,setError]=useState("");
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");try{await register(form);nav("/workspace")}catch(err){setError(err instanceof Error?err.message:"Unable to create workspace")}};
  return <div className="auth-story"><div className="auth-story-side register-side"><Link to="/" className="auth-brand"><span>∞</span> Infinity Labs</Link><div className="auth-story-copy"><span>START SOMETHING CONNECTED</span><h1>Your company,<br/><em>in flow.</em></h1><p>Create a workspace for customers, projects, tasks, and the work between them.</p></div><div className="auth-story-footer">NEXUSFLOW / BUSINESS OPERATING WORKSPACE</div></div><div className="auth-form-side"><div className="auth-form-box"><Link to="/" className="back-link">← Back to company</Link><div className="auth-symbol"><Infinity size={26}/></div><span className="workspace-kicker">NEXUSFLOW WORKSPACE</span><h2>Create your workspace.</h2><p>Start with your company and grow from there.</p>{error&&<div className="auth-error">{error}</div>}<form onSubmit={submit}><label>Your name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Lucas Tan" required/></label><label>Work email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@company.com" required/></label><label>Company name<input value={form.companyName} onChange={e=>setForm({...form,companyName:e.target.value})} placeholder="Infinity Labs Technologies LLC" required/></label><label>Password<input type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters" required/></label><button className="workspace-button full">Create workspace <ArrowRight size={17}/></button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></div></div></div>;
}
